import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { getCsrfToken } from "../csrf-client";

export const Route = createFileRoute("/contact")({ component: ContactPage });
const topics = [["support", "Support"], ["safety", "Safety"], ["privacy", "Privacy/Data"], ["billing", "Billing & Refunds"], ["dmca", "DMCA/Copyright"], ["other", "Other"]] as const;
function ContactPage() {
  const [form, setForm] = useState({ name: "", email: "", topic: "support", message: "" });
  const [status, setStatus] = useState<string | null>(null); const [busy, setBusy] = useState(false);
  const submit = async (e: React.FormEvent) => { e.preventDefault(); setBusy(true); setStatus(null); try { await fetch("/api/csrf"); const token = getCsrfToken(); const res = await fetch("/api/contact", { method: "POST", headers: { "Content-Type": "application/json", ...(token ? { "X-CSRF-Token": token } : {}) }, body: JSON.stringify(form) }); const data = await res.json(); if (!res.ok) throw new Error(data.error || "Unable to send message."); setStatus("Thanks — we've received your message and will get back to you."); setForm({ name: "", email: "", topic: "support", message: "" }); } catch (err) { setStatus(err instanceof Error ? err.message : "Unable to send message."); } finally { setBusy(false); } };
  return <div className="mx-auto max-w-3xl px-4 py-16"><h1 className="mb-3 text-3xl font-bold text-white">Contact Us</h1><p className="mb-10 text-gray-400">Questions, feedback, or need help? Our team reads every message.</p>
    <form onSubmit={submit} className="card space-y-5 border-rose-500/20 p-6"><label className="block"><span className="mb-2 block text-sm text-gray-300">Name <span className="text-gray-500">(optional)</span></span><input value={form.name} maxLength={120} onChange={e => setForm({...form, name:e.target.value})} className="input w-full" /></label><label className="block"><span className="mb-2 block text-sm text-gray-300">Email <span className="text-rose-400">*</span></span><input required type="email" value={form.email} onChange={e => setForm({...form, email:e.target.value})} className="input w-full" /></label><label className="block"><span className="mb-2 block text-sm text-gray-300">Topic</span><select value={form.topic} onChange={e => setForm({...form, topic:e.target.value})} className="input w-full">{topics.map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="block"><span className="mb-2 block text-sm text-gray-300">Message <span className="text-rose-400">*</span></span><textarea required maxLength={4000} rows={7} value={form.message} onChange={e => setForm({...form, message:e.target.value})} className="input w-full resize-y" /></label><button disabled={busy} className="btn-primary disabled:opacity-50">{busy ? "Sending…" : "Send message"}</button>{status && <p role="status" className="text-sm text-gray-300">{status}</p>}</form>
    <div className="mt-12 space-y-3 text-gray-400"><h2 className="text-xl font-semibold text-white">Other ways to get help</h2><p>For safety issues, use in-app <Link to="/safety" className="text-rose-400 underline">Report</Link> buttons on profiles, matches, and chat.</p><p>See our <Link to="/data" className="text-rose-400 underline">data-rights</Link> and <Link to="/refund" className="text-rose-400 underline">refund</Link> pages.</p><p>For copyright notices, visit our <Link to="/dmca" className="text-rose-400 underline">DMCA page</Link>.</p></div><div className="mt-10"><Link to="/" className="text-sm text-rose-400">← Back to GradeDate</Link></div></div>;
}
